### ISSUE TITLE
ag-grid-community version 30

### ISSUE THREAD

**Issue by isaacwein** [MichaelKim/ag-grid-svelte#11]
ag-grid-community version 30 has been released can this project work with it

**Comment by MichaelKim** [comment]
I'll take a look at v30 and see if there's any changes needed here.

**Comment by codeoutin** [comment]
I would love to see this since the new features look very promising. Thank you for your work @MichaelKim !

**Comment by MichaelKim** [comment]
I'm glad to hear that! I've been slowly going over the v30 changelog to check for breaking changes, but I should be able to get a release out soon.

**Comment by MichaelKim** [comment]
ag-grid-svelte@0.3.0 now supports AG Grid v30. Make sure to use at least ag-grid-community@30.0.3 to avoid build errors (see https://github.com/ag-grid/ag-grid/issues/6744 for more info). If you encounter any issues, please feel free to create a new issue.

**Comment by isaacwein** [comment]
Thank you very much
