### ISSUE TITLE
Doesn't work with VITE, mode development and package "entreprise"

### ISSUE THREAD

**Issue by frck006** [MichaelKim/ag-grid-svelte#2]
Hi, 

Juste to say, there are a problem with the component when I compile with **VITE** in **development** mode.
I want to use the license "**entreprise**" about AgGrid.
The problem: features "entreprise" doesn't work, like "columns" panel or column with hierarchical, no alert message about license in the console, ...
I import the component dynamically with "await import". 
At this moment, I see in "network" tab from Chrome, le module "entreprise" and after "community".
Perhaps "community" replace something. (I don't know)

But, if I change the name of the package in "AgGridSvelte" like below,=> **it works** :)
  
![image](https://user-images.githubusercontent.com/10244725/202179780-f81d8986-458a-46cd-b21b-60320e04dde0.png)

**Comment by MichaelKim** [comment]
Thanks for the report! I think this has to do with Vite pre-bundling dependencies. Could you try:

- [Clearing your Vite cache](https://vitejs.dev/guide/dep-pre-bundling.html#file-system-cache) (run `vite dev --force` or delete `node_modules/.vite/`), or
- Adding `ag-grid-svelte` to [`optimize.include`](https://vitejs.dev/config/dep-optimization-options.html#optimizedeps-include) in your Vite config (or `ag-grid-community` if that doesn't work)

**Comment by frck006** [comment]
Thank you for this information.

It works with `"--force"` option..

**Comment by MichaelKim** [comment]
Glad that helped, I'll update the docs with more info for working with enterprise AG Grid.
