### ISSUE TITLE
unmet peer ag-grid-community@^28: found 29.0.0

### ISSUE THREAD

**Issue by brunobely** [MichaelKim/ag-grid-svelte#5]
Got this warning when running the install command recommended in the guide: `npm install ag-grid-community ag-grid-svelte`.

```
  └── ✕ unmet peer ag-grid-community@^28: found 29.0.0
```

 Wondering if this is a quick upgrade or if more involved. But FYI maybe the guide could be updated so that ag-grid-community@^28 is recommended instead?

**Comment by MichaelKim** [comment]
I went through the 29.0.0 changelog and didn't find any breaking changes to `GridOptions`, mostly removing deprecated properties, so it should be safe to ignore the warning for now. Once I test it locally, I can make a release to add 29 as a peer dependency.

**Comment by MichaelKim** [comment]
While v29 seems to work fine, there are possible type errors when using some of the changed `GridOptions` props with TypeScript.  Supporting multiple versions probably requires publishing a version for each major version of AG Grid, so for now I'll recommend sticking with v28. I also added a note to the guide about using v29.
