### ISSUE TITLE
I am unable to get the sideBar to render using  Enterprise

### ISSUE THREAD

**Issue by doghousedev** [MichaelKim/ag-grid-svelte#7]
I have tried the steps listed on the docs but it doesn't render the side bar. 

i have imported 'ag-grid-enterprise' before rendering the grid
I have tried  'npm run dev '--force'  
I have modified the vite.config.ts to include the 'optimize:include'

The enterprise watermark does show in the console, however no Enterprise features seem to be enabled. 

I am using version 29.0

**Comment by MichaelKim** [comment]
Could you provide a small example of your code? I got it working by importing `ag-grid-enterprise` and setting the `sideBar` prop to true:

```svelte
<script>
  import AgGridSvelte from 'ag-grid-svelte';
  import 'ag-grid-community/styles/ag-grid.css';
  import 'ag-grid-community/styles/ag-theme-alpine.css';
  import 'ag-grid-enterprise';

  const columnDefs = [{ field: 'a' }, { field: 'b' }];

  const rowData = [
    { a: 1, b: 2 },
    { a: 3, b: 4 }
  ];
</script>

<div style:height="500px" class="ag-theme-alpine">
  <AgGridSvelte {rowData} {columnDefs} sideBar />
</div>
```

**Comment by doghousedev** [comment]
Thanks, That did enable it.

Such a simple solution.

Thank you again

Ron
