### ISSUE TITLE
Peer conflict with ag-grid 29

### ISSUE THREAD

**Issue by bfovez** [MichaelKim/ag-grid-svelte#9]
See the error when I try to **npm i ag-grid-svelte**  when ag-grid 29 is already installed:

> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: --------@0.0.1
> npm ERR! Found: ag-grid-community@29.3.3
> npm ERR! node_modules/ag-grid-community
> npm ERR!   dev ag-grid-community@"^29.3.3" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer ag-grid-community@"^28" from ag-grid-svelte@0.1.4
> npm ERR! node_modules/ag-grid-svelte
> npm ERR!   ag-grid-svelte@"*" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!

**Comment by MichaelKim** [comment]
It should be safe to ignore the version warning as the package works with AG Grid v29. I'll make a release shortly that adds the new version to the peer deps.

**Comment by MichaelKim** [comment]
Should be resolved with `ag-grid-svelte@0.2.0`, feel free to re-raise if you're still encountering the error.

**Comment by bfovez** [comment]
Thank you !
